num1 = input ("Enter number 1:")
num2 = input ("Enter number 2:")
sum=int(num1)+int(num2)
diff=int(num1)-int(num2)
prod=int(num1)*int(num2)
qou=int(num1)/int(num2)
rem=int(num1)%int(num2)
print("Results:")
print(num1,"+",num2,"=",sum)
print(num1,"-",num2,"=",diff)
print(num1,"x",num2,"=",prod)
print(num1,"/",num2,"=",qou)
print(num1,"%",num2,"=",rem)